-- Seekigo: public.event_sources
-- 1イベントに複数情報源（gotokyo / enjoytokyo 等）を紐付ける。
--
-- 実行: Supabase SQL Editor に貼り付けて実行（このファイル自体は自動実行しない）
-- 前提: public.events.id は bigint（identity）
--
-- 注意:
-- - public.events.source_url は後方互換のため当面残す（削除しない）
-- - 書き込みは service_role のみ（RLS 有効 + 公開ロールに write ポリシーなし）
-- - service_role は RLS をバイパスするため insert/update/delete 可能

CREATE TABLE IF NOT EXISTS public.event_sources (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id bigint NOT NULL REFERENCES public.events (id) ON DELETE CASCADE,
  source_name text NOT NULL,
  source_url text NOT NULL,
  source_event_id text,
  official_url text,
  last_checked_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT event_sources_source_name_check
    CHECK (source_name IN ('gotokyo', 'enjoytokyo', 'walkerplus')),
  CONSTRAINT event_sources_event_source_url_unique
    UNIQUE (event_id, source_name, source_url)
);

CREATE INDEX IF NOT EXISTS event_sources_event_id_idx
  ON public.event_sources (event_id);

CREATE INDEX IF NOT EXISTS event_sources_source_name_url_idx
  ON public.event_sources (source_name, source_url);

COMMENT ON TABLE public.event_sources IS
  'Multiple source links per event (gotokyo, enjoytokyo, ...). Writes via service_role only.';

COMMENT ON COLUMN public.event_sources.source_name IS
  'Source key: gotokyo | enjoytokyo | walkerplus';

COMMENT ON COLUMN public.event_sources.source_event_id IS
  'Provider-side id when available (e.g. EnjoyTokyo /event/2074515/ → 2074515)';

-- updated_at 自動更新
CREATE OR REPLACE FUNCTION public.set_event_sources_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_event_sources_updated_at ON public.event_sources;
CREATE TRIGGER trg_event_sources_updated_at
  BEFORE UPDATE ON public.event_sources
  FOR EACH ROW
  EXECUTE FUNCTION public.set_event_sources_updated_at();

-- RLS: 公開ロールからの直接書き込みを禁止
ALTER TABLE public.event_sources ENABLE ROW LEVEL SECURITY;

-- 既存ポリシーがあれば作り直し（再実行安全）
DROP POLICY IF EXISTS "event_sources_select_public" ON public.event_sources;
DROP POLICY IF EXISTS "event_sources_no_insert_anon" ON public.event_sources;
DROP POLICY IF EXISTS "event_sources_no_update_anon" ON public.event_sources;
DROP POLICY IF EXISTS "event_sources_no_delete_anon" ON public.event_sources;
DROP POLICY IF EXISTS "event_sources_no_insert_authenticated" ON public.event_sources;
DROP POLICY IF EXISTS "event_sources_no_update_authenticated" ON public.event_sources;
DROP POLICY IF EXISTS "event_sources_no_delete_authenticated" ON public.event_sources;

-- 読み取りのみ公開（将来ソース表示用）。書き込みポリシーは作らない。
CREATE POLICY "event_sources_select_public"
  ON public.event_sources
  FOR SELECT
  TO anon, authenticated
  USING (true);

-- 明示的に write を拒否（ポリシー未定義でも RLS 下では拒否されるが意図を文書化）
-- ※ service_role は RLS をバイパスするため影響なし

REVOKE INSERT, UPDATE, DELETE ON public.event_sources FROM anon, authenticated;
GRANT SELECT ON public.event_sources TO anon, authenticated;
GRANT ALL ON public.event_sources TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.event_sources_id_seq TO service_role;
