-- Seekigo Phase 2.6: minato_opendata を source として保存できるようにし、
-- 複数開催日用の event_occurrences を空の子テーブルとして追加する。
--
-- 実行: Supabase SQL Editor に貼り付けて手動実行（このファイルは自動実行しない）
-- 既存 events / event_sources / event_dedupe_reviews の行は UPDATE・DELETE・backfill しない。
--
-- 適用前に制約名を確認する（本番の名前がリポジトリと違うと DROP が空振りする）:
--   SELECT conname, pg_get_constraintdef(oid)
--   FROM pg_constraint
--   WHERE conrelid IN (
--     'public.event_sources'::regclass,
--     'public.event_dedupe_reviews'::regclass
--   )
--   AND contype = 'c'
--   AND (
--     pg_get_constraintdef(oid) ILIKE '%source_name%'
--     OR pg_get_constraintdef(oid) ILIKE '%incoming_source_name%'
--   );
-- リポジトリ上の名前:
--   event_sources_source_name_check
--   event_dedupe_reviews_incoming_source_name_check

-- ─── source_name ─────────────────────────────────────────────

ALTER TABLE public.event_sources
  DROP CONSTRAINT IF EXISTS event_sources_source_name_check;

ALTER TABLE public.event_sources
  ADD CONSTRAINT event_sources_source_name_check
  CHECK (source_name IN ('gotokyo', 'enjoytokyo', 'walkerplus', 'minato_opendata'));

COMMENT ON COLUMN public.event_sources.source_name IS
  'Source key: gotokyo | enjoytokyo | walkerplus | minato_opendata';

ALTER TABLE public.event_dedupe_reviews
  DROP CONSTRAINT IF EXISTS event_dedupe_reviews_incoming_source_name_check;

ALTER TABLE public.event_dedupe_reviews
  ADD CONSTRAINT event_dedupe_reviews_incoming_source_name_check
  CHECK (incoming_source_name IN ('gotokyo', 'enjoytokyo', 'walkerplus', 'minato_opendata'));

-- ─── dataset_url（CC BY の配布ファイル URL）────────────────

ALTER TABLE public.event_sources
  ADD COLUMN IF NOT EXISTS dataset_url text;

COMMENT ON COLUMN public.event_sources.dataset_url IS
  'Machine-readable dataset URL for attribution (e.g. Minato open-data CSV). Distinct from source_url (page) and official_url.';

-- ─── event_occurrences ───────────────────────────────────────
-- 出典は event_sources が持つ。この表に source_name は置かない。
-- 既存 events.start_date / end_date は維持する。既存行のコピーはしない。

CREATE TABLE IF NOT EXISTS public.event_occurrences (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  event_id bigint NOT NULL
    REFERENCES public.events (id)
    ON DELETE CASCADE,

  start_date date NOT NULL,
  end_date date NOT NULL,
  start_time time NULL,
  end_time time NULL,

  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT event_occurrences_end_on_or_after_start
    CHECK (end_date >= start_date),

  -- PostgreSQL 15 以降。NULL の時刻も「同じ値」として重複を拒否する。
  -- Supabase の現行プロジェクトは PostgreSQL 15 以上が前提。
  -- 15 未満で CREATE が失敗する場合は、この制約を外し、末尾コメントの代替案を使う。
  CONSTRAINT event_occurrences_session_unique
    UNIQUE NULLS NOT DISTINCT (event_id, start_date, end_date, start_time, end_time)
);

CREATE INDEX IF NOT EXISTS event_occurrences_event_start_idx
  ON public.event_occurrences (event_id, start_date);

-- 「今日 / 今週末 / 次回」を event_id なしで日付範囲検索するため。
-- (event_id, start_date) では、日付だけを条件にした検索の index にはならない。
CREATE INDEX IF NOT EXISTS event_occurrences_start_date_idx
  ON public.event_occurrences (start_date);

COMMENT ON TABLE public.event_occurrences IS
  'Discrete sessions for one event. Do not store separate dates as a single start_date..end_date span. Empty until an importer writes rows. Source attribution stays on event_sources.';

-- updated_at: 共通関数はない。event_sources と同じ表ごとの関数にする。
CREATE OR REPLACE FUNCTION public.set_event_occurrences_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_event_occurrences_updated_at
  ON public.event_occurrences;
CREATE TRIGGER trg_event_occurrences_updated_at
  BEFORE UPDATE ON public.event_occurrences
  FOR EACH ROW
  EXECUTE FUNCTION public.set_event_occurrences_updated_at();

-- RLS: 公開ページはまだ occurrences を直接読まない。
-- event_dedupe_reviews と同じく service_role のみ。anon / authenticated に SELECT は付けない。
-- GRANT ALL だけでなく、列権限と identity sequence を明示する。
-- Supabase では sequence 名が想定と違うと INSERT だけ permission denied になる。
ALTER TABLE public.event_occurrences ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.event_occurrences FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.event_occurrences TO service_role;

DO $$
DECLARE
  seq regclass;
BEGIN
  seq := pg_get_serial_sequence('public.event_occurrences', 'id')::regclass;
  IF seq IS NOT NULL THEN
    EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO service_role', seq);
  END IF;
END $$;

-- ─── rollback（実行しない）──────────────────────────────────
-- DROP TABLE IF EXISTS public.event_occurrences;
-- DROP FUNCTION IF EXISTS public.set_event_occurrences_updated_at();
--
-- ALTER TABLE public.event_sources DROP COLUMN IF EXISTS dataset_url;
--
-- ALTER TABLE public.event_sources
--   DROP CONSTRAINT IF EXISTS event_sources_source_name_check;
-- ALTER TABLE public.event_sources
--   ADD CONSTRAINT event_sources_source_name_check
--   CHECK (source_name IN ('gotokyo', 'enjoytokyo', 'walkerplus'));
--
-- ALTER TABLE public.event_dedupe_reviews
--   DROP CONSTRAINT IF EXISTS event_dedupe_reviews_incoming_source_name_check;
-- ALTER TABLE public.event_dedupe_reviews
--   ADD CONSTRAINT event_dedupe_reviews_incoming_source_name_check
--   CHECK (incoming_source_name IN ('gotokyo', 'enjoytokyo', 'walkerplus'));
--
-- occurrence に行が入ったあとの DROP TABLE は、その開催日を捨てる。

-- ─── NULLS NOT DISTINCT が使えない場合（PostgreSQL 14 以前）──
-- UNIQUE NULLS NOT DISTINCT は PostgreSQL 15 で追加された。
-- 14 以前では CREATE TABLE の該当 CONSTRAINT を外し、次で代用する。
-- start_time / end_time が両方 NULL の同一日を 1 件に限る。
-- 本物の 00:00 と NULL を区別したいので、coalesce で 00:00 に潰さない。
--
-- ALTER TABLE public.event_occurrences
--   ADD COLUMN start_time_key text
--     GENERATED ALWAYS AS (COALESCE(start_time::text, '')) STORED,
--   ADD COLUMN end_time_key text
--     GENERATED ALWAYS AS (COALESCE(end_time::text, '')) STORED;
-- ALTER TABLE public.event_occurrences
--   ADD CONSTRAINT event_occurrences_session_unique
--   UNIQUE (event_id, start_date, end_date, start_time_key, end_time_key);
