-- Seekigo: 動作確認用 東京イベント 10件 seed
-- 既存行は削除しない。slug 重複時は UPSERT（要: public.events.slug の UNIQUE）
-- 実行例: Supabase SQL Editor に貼り付けて実行（このファイル自体は自動実行しない）

INSERT INTO public.events (
  title,
  slug,
  official_url,
  source_url,
  venue,
  area,
  address,
  start_date,
  end_date,
  start_time,
  end_time,
  price_text,
  is_free,
  is_indoor,
  is_kids,
  is_night,
  category,
  summary,
  image_url,
  status,
  last_checked_at
) VALUES
(
  'TOKYO SEA LIGHT',
  'tokyo-sea-light-2026',
  NULL,
  'https://www.gotokyo.org/en/spot/ev370/index.html',
  'WATERS takeshiba・Hi-NODE・お台場周辺',
  'odaiba',
  NULL,
  '2026-05-20',
  '2026-08-29',
  '18:30',
  '21:30',
  '2,000円 ※内容により異なるため最新情報は公式確認',
  false,
  false,
  false,
  true,
  ARRAY['illumination', 'nightlife']::text[],
  '竹芝・芝浦・お台場のウォーターフロントを青い光でつなぐ期間限定イルミネーションイベント。',
  NULL,
  'published',
  NULL
),
(
  '原宿表参道元氣祭スーパーよさこい2026',
  'harajuku-omotesando-super-yosakoi-2026',
  NULL,
  'https://www.gotokyo.org/en/spot/ev067/index.html',
  '原宿・表参道・代々木公園周辺',
  'shibuya',
  NULL,
  '2026-08-29',
  '2026-08-30',
  NULL,
  NULL,
  '無料',
  true,
  false,
  true,
  false,
  ARRAY['festival', 'traditional']::text[],
  '原宿・表参道エリアを舞台に全国のよさこいチームが演舞を披露する、東京最大級のよさこいイベント。',
  NULL,
  'published',
  NULL
),
(
  '第67回東京高円寺阿波おどり',
  'tokyo-koenji-awaodori-2026',
  NULL,
  'https://www.gotokyo.org/jp/spot/ev039/index.html',
  'JR高円寺駅・新高円寺駅周辺',
  'koenji',
  NULL,
  '2026-08-29',
  '2026-08-30',
  NULL,
  NULL,
  '詳細は公式サイト確認',
  false,
  false,
  true,
  true,
  ARRAY['festival', 'traditional']::text[],
  '高円寺の街を舞台に多数の踊り手が参加する、東京を代表する夏の阿波おどり。',
  NULL,
  'published',
  NULL
),
(
  '特別展「大南極展」',
  'great-antarctic-exhibition-2026',
  NULL,
  'https://www.gotokyo.org/jp/see-and-do/arts-and-design/art-and-exhibitions/index.html',
  '日本科学未来館',
  'odaiba',
  NULL,
  '2026-07-01',
  '2026-09-27',
  NULL,
  NULL,
  '一般2,000円',
  false,
  true,
  true,
  false,
  ARRAY['exhibition', 'science', 'kids']::text[],
  '南極観測70周年をテーマに、南極の氷や隕石、観測資料、体験展示などを紹介する特別展。',
  NULL,
  'published',
  NULL
),
(
  '開館50周年記念 山口華楊展',
  'yamaguchi-kayo-retrospective-2026',
  NULL,
  'https://www.gotokyo.org/jp/see-and-do/arts-and-design/art-and-exhibitions/index.html',
  'SOMPO美術館',
  'shinjuku',
  NULL,
  '2026-07-11',
  '2026-08-30',
  NULL,
  NULL,
  '一般1,600円 ※最新料金は公式確認',
  false,
  true,
  false,
  false,
  ARRAY['exhibition', 'art']::text[],
  '動物画で知られる日本画家・山口華楊の初期から晩年までを代表作でたどる回顧展。',
  NULL,
  'published',
  NULL
),
(
  '企画展「かみ×つくる ～紙づくり・じっけん・工作にチャレンジ！～」',
  'kami-tsukuru-paper-museum-2026',
  NULL,
  'https://www.gotokyo.org/jp/see-and-do/arts-and-design/art-and-exhibitions/index.html',
  '紙の博物館',
  'oji',
  NULL,
  '2026-07-18',
  '2026-08-30',
  NULL,
  NULL,
  '一般400円',
  false,
  true,
  true,
  false,
  ARRAY['exhibition', 'kids', 'workshop']::text[],
  '紙づくりや工作、実験を通して紙の仕組みや面白さを学べる夏休み向け企画展。',
  NULL,
  'published',
  NULL
),
(
  '特別展「いきもの超ワールド展 国立科学博物館×ダーウィンが来た！」',
  'ikimono-super-world-2026',
  NULL,
  'https://www.gotokyo.org/jp/see-and-do/arts-and-design/art-and-exhibitions/index.html',
  '国立科学博物館',
  'ueno',
  NULL,
  '2026-07-11',
  '2026-10-12',
  NULL,
  NULL,
  '一般2,300円',
  false,
  true,
  true,
  false,
  ARRAY['exhibition', 'science', 'kids']::text[],
  '生物の進化と生存戦略を、博物館の標本や研究資料と自然番組の映像を組み合わせて紹介する特別展。',
  NULL,
  'published',
  NULL
),
(
  '創設90年記念 琉球王国の染織',
  'ryukyu-textiles-2026',
  NULL,
  'https://www.gotokyo.org/jp/see-and-do/arts-and-design/art-and-exhibitions/index.html',
  '日本民藝館',
  'meguro',
  NULL,
  '2026-08-22',
  '2026-11-03',
  NULL,
  NULL,
  '一般1,500円',
  false,
  true,
  false,
  false,
  ARRAY['exhibition', 'art', 'traditional']::text[],
  '琉球王国ゆかりの紅型や織物を中心に、沖縄の染織文化を紹介する日本民藝館創設90年記念展。',
  NULL,
  'published',
  NULL
),
(
  'メキシコに生きる版画家 竹田鎭三郎：起源を求めて',
  'shinaburo-takeda-mexico-2026',
  NULL,
  'https://www.gotokyo.org/jp/see-and-do/arts-and-design/art-and-exhibitions/index.html',
  '町田市立国際版画美術館',
  'machida',
  NULL,
  '2026-06-19',
  '2026-08-30',
  NULL,
  NULL,
  '無料',
  true,
  true,
  false,
  false,
  ARRAY['exhibition', 'art', 'free']::text[],
  'メキシコを拠点に活動してきた画家・版画家、竹田鎭三郎の作品を紹介する展覧会。',
  NULL,
  'published',
  NULL
),
(
  '第25回 Fiesta Mexicana 2026 in お台場Tokyo',
  'fiesta-mexicana-odaiba-2026',
  NULL,
  'https://www.gotokyo.org/en/spot/ev086/index.html',
  'お台場デッキ',
  'odaiba',
  NULL,
  '2026-09-20',
  '2026-09-22',
  '11:00',
  '19:00',
  '入場無料 ※飲食・物販・一部体験は有料',
  true,
  false,
  true,
  false,
  ARRAY['festival', 'food', 'kids']::text[],
  'メキシコ音楽やダンス、料理、雑貨、ルチャリブレなどをお台場で楽しめる3日間の文化イベント。',
  NULL,
  'published',
  NULL
)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  official_url = EXCLUDED.official_url,
  source_url = EXCLUDED.source_url,
  venue = EXCLUDED.venue,
  area = EXCLUDED.area,
  address = EXCLUDED.address,
  start_date = EXCLUDED.start_date,
  end_date = EXCLUDED.end_date,
  start_time = EXCLUDED.start_time,
  end_time = EXCLUDED.end_time,
  price_text = EXCLUDED.price_text,
  is_free = EXCLUDED.is_free,
  is_indoor = EXCLUDED.is_indoor,
  is_kids = EXCLUDED.is_kids,
  is_night = EXCLUDED.is_night,
  category = EXCLUDED.category,
  summary = EXCLUDED.summary,
  image_url = EXCLUDED.image_url,
  status = EXCLUDED.status,
  last_checked_at = EXCLUDED.last_checked_at,
  updated_at = now();
